---
- hosts: localhost
  connection: localhost
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - tmux
        - vim-nox

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: robin
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: robin
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc files
    copy:
      src: files/bashrc
      dest: /home/robin/.bashrc
      owner: robin
      group: robin
      
  - name: add ansible user
    user:
      name: ansudo
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansudo
      dest: /etc/sudoers.d/ansudo
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansudo
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/RobinPoirier/pc-config.git