---
- hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  # - name: create temp directory
  #   ansible.builtin.file:
  #     path: /home/robin/.tmp
  #     state: directory
  #     mode: 0755

  # - name: Download starship
  #   ansible.builtin.get_url:
  #     url: http://starship.rs/install.sh
  #     dest: /home/robin/.tmp/install.sh

  # - name: install starship
  #   ansible.builtin.shell:
  #     cmd: cat /home/robin/.tmp/install.sh | sh -s -- --yes --bin-dir /data/data/com.termux/files/usr/bin

  # - include_tasks: tasks/users.yml
  # - include_tasks: tasks/cron.yml
  # - include_tasks: tasks/packages.yml
  # - include_tasks: tasks/curlapps.yml
  # - include_tasks: tasks/config-files.yml

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]