- name: install packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - git
      - curl
      - htop
      - mc
      - neofetch
      - rsync
      - tmux
      - traceroute
      - wget
      - whois
      - zsh
      - nala
      - getconf