[shlvl]
disabled = false
threshold = 1
symbol = "↕️ "

[shell]
disabled = false
bash_indicator = ""
powershell_indicator = ""
cmd_indicator = ""

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = ""
symbols.Windows = ""
